import Head from "next/head";
import Hero from "../components/Hero";
import Contact from "../components/Contact";
import Services from "../components/Services";
import Team from "../components/Team";
import Finisher from "../components/Finisher";
import About from "../components/About";
import Clients from "../components/Clients";
import Accreditions from "../components/Accredition";
import Laboratories from "../components/Laboratories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Services />
      <Clients />
      <Laboratories />
      <Accreditions />
      <About />

      <Contact />
    </div>
  );
}
